---
- name: ctf setup
  hosts: localhost
  become: yes

  tasks:
    - name: Install Python3 and pip
      apt:
        name: 
          - python3
          - python3-pip
        state: present

    - name: Install python packages
      pip:
        name: 
          - pwntools
          - pycryptodome
          - angr
          - ropper
        state: present

    - name: Install basic pentesting & CTF-s tools
      apt:
        name:
          - nmap
          - sqlmap
          - ncat
          - steghide
          - binwalk
          - hashcat
          - john
          - dirbuster
          - ffuf
          - tmux
          - gcc-multilib
          - gdb-multiarch
          - qemu-user-static
          - ruby
          - rubygems
          - docker.io
          - nodejs
          - npm
          - patchelf
          - cargo
          - elfutils
        state: present

    - name: Install peda-gef-pwndbg
      shell: |
        cd ~
        git clone https://github.com/apogiatzis/gdb-peda-pwndbg-gef.git
        cd gdb-peda-pwndbg-gef
        ./install.sh

    - name: Install one_gadget
      gem:
        name: one_gadget
        state: present

    - name: Download pwninit
      shell: |
        wget https://github.com/io12/pwninit/releases/download/3.3.1/pwninit
        chmod +x pwninit
        mv pwninit /opt/pwninit
        echo 'alias=pwninit' >> ~/.bashrc
        source ~/.bashrc
